version: '3.3'
services:
  video-processor-go:
    build:
      context: .
      dockerfile: Dockerfile
    image: video-processor:latest
    volumes:
      - /home/shared/video_processing_log:/app/log
      - /home/shared/unprocessed_videos:/home/shared/unprocessed_videos
      - /home/shared/processed_videos:/home/shared/processed_videos
    ports:
      - "30016:30016"
    env_file:
      - .env
    container_name: video-processor-go
